spring:
  logging:
    path: logs
    level:
      root: DEBUG
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5001/microcard
    username: postgres
    password: postgres
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 10000
  cache:
    type: redis
#mybatis
rest:
  http:
    connect-timeout: 30000
    read-timeout: 30000
    write-timeout: 600
    max-idle-connections: 200
    keep-alive-duration: 300
#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/*/*.xml
  global-config:
    id-type: 2
    field-strategy: 2
    db-column-underline: true
    refresh-mapper: true
    logic-delete-value: 0
    logic-not-delete-value: 1
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false