spring:
  logging:
    path: logs
    level:
      root: DEBUG
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5001/microcard
    username: postgres
    password: postgres
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 10000
  cache:
    type: redis