spring:
  application:
    name: spring-loan-service-dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bakong
    username: postgres
    password: postgres
  logging:
    path: /var/logs/bakongapi
    level:
      root: DEBUG
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 10000
  cache:
    type: redis
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    listener:
      simple:
        default-requeue-rejected: false
        retry:
          enabled: false
          max-attempts: 1
          initial-interval: 5000
nbcinterface:
  profile: dev